Update next-step.md
LIPS-scheme/lips pull request #403
Opened 2024-10-31 16:58 UTC by ArshadAriff

Updated next-step.md

2024-10-31 16:58 UTC, ArshadAriff commented
@jcubic sir!

2024-10-31 17:26 UTC, jcubic requested changes

2024-10-31 17:26 UTC, jcubic commented on docs/docs/scheme-intro/next-step.md
> +I also recommend video lectures, with two versions available. The original by Abelson and Sussman from 1986 is highly recommended.
I don't like the phrase: "is highly recommended" here.

2024-10-31 17:26 UTC, jcubic commented on docs/docs/scheme-intro/next-step.md
> +For more on Lisp macros, these two books are highly recommended:
Same, I don't like the "are highly recommended" and changing the sentence.

This doesn't look like a grammar fix.

2024-10-31 17:33 UTC, ArshadAriff commented
Done Sir!

2024-10-31 17:37 UTC, ArshadAriff commented
@jcubic anything else sir!

2024-10-31 18:22 UTC, ArshadAriff commented
@jcubic sir i have only 10 mins left for the day to end sir!

2024-10-31 18:44 UTC, merged

2024-10-31 19:05 UTC, ArshadAriff commented
@jcubic sir Hope to work with you in future!🙂

2024-11-01 11:20 UTC, ArshadAriff commented
@jcubic sir i think hacktoberfest acceptable label is necessary for every PR submitted can you add it to my 4 PRs sir!